### ISSUE TITLE
Backend won't start getting this error 

### ISSUE THREAD

**Issue by mylastore** [antony/sapper-authentication-demo#1]
First of all thank you for putting this together, I am managing my jwt-token in the client side of sapper and found your tutorial witch is awesome and necessary to clear my head about having client and server running for a front end ;)

Back end server won't start for me.
```
/Users/oscar/Downloads/sapper-authentication-demo-master/backend/node_modules/@hapi/hapi/lib/core.js:51
    actives = new WeakMap(); 

SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/oscar/Downloads/sapper-authentication-demo-master/backend/node_modules/@hapi/hapi/lib/server.js:9:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
```

**Comment by mylastore** [comment]
I just find that issue in hapi and it looks like I need node v 14

**Comment by mylastore** [comment]
It worked with node 14 closing issue.
