### ISSUE TITLE
I am getting this error when I run npm run dev

### ISSUE THREAD

**Issue by mylastore** [antony/sapper-authentication-demo#7]
I downloaded the repo and npm i on both backend and root an getting the error below. 

```
✗ client
'import' and 'export' may only appear at the top level
11: }
12: 
13: export function connect(port) {
    ^
14:   if (source || !window.EventSource) return;
✗ server
'import' and 'export' may only appear at the top level
11: }
12: 
13: export function connect(port) {
    ^
14:   if (source || !window.EventSource) return;
✔ service worker (188ms)
internal/modules/cjs/loader.js:969
    throw err;
    ^

Error: Cannot find module '/storage/sapper-authentication-demo-master/__sapper__/dev/server/server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:17)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
> Server crashed
```

**Comment by mylastore** [comment]
Update the above happen only when I downloaded the repo but when I use git clone it work perfect.

**Comment by antony** [comment]
@mylastore https://github.com/rollup/plugins/issues/304
